In [1]:
import pandas as pd
import numpy as numpy

In [5]:
movi=pd.read_csv('imdb-top-1000.csv')
movi

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [3]:
ipl=pd.read_csv('ipl-matches.csv')
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [9]:
# groupby
geners=movi.groupby('Genre')

In [7]:
movi.head(5)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [10]:
geners.sum()

C:\Users\theve\AppData\Local\Temp\ipykernel_19108\1361745514.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  geners.sum()

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [11]:
len(geners)

14

In [12]:
geners.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [13]:
geners.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [14]:
geners.nth(7)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Star Wars,1977,121,8.6,George Lucas,Mark Hamill,1231473,322740140.0,90.0
Adventure,Queen,2013,146,8.2,Vikas Bahl,Kangana Ranaut,60701,1429534.0,NaN
Animation,Mononoke-hime,1997,134,8.4,Hayao Miyazaki,YÃ´ji Matsuda,343171,2375308.0,76.0
Biography,Amadeus,1984,160,8.3,Milos Forman,F. Murray Abraham,369007,51973029.0,88.0
Comedy,AmÃ©lie,2001,122,8.3,Jean-Pierre Jeunet,Audrey Tautou,703810,33225499.0,69.0
Crime,The Silence of the Lambs,1991,118,8.6,Jonathan Demme,Jodie Foster,1270197,130742922.0,85.0
Drama,Whiplash,2014,106,8.5,Damien Chazelle,Miles Teller,717585,13092000.0,88.0
Horror,Halloween,1978,91,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
Mystery,The Lady Vanishes,1938,96,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0

In [15]:
geners.get_group("Horror")

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro AmenÃ¡bar,Nicole Kidman,337651,96522687.0,74.0

In [16]:
geners.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [18]:
geners.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [21]:
geners.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
375,Mou gaan dou,2002,101,Action,8.0,Andrew Lau,Alan Mak,117857,169659.0,75.0
914,Sherlock Holmes,2009,128,Action,7.6,Guy Ritchie,Robert Downey Jr.,583158,209028679.0,57.0
618,The Hobbit: An Unexpected Journey,2012,169,Adventure,7.8,Peter Jackson,Martin Freeman,757377,303003568.0,58.0
739,Nebraska,2013,115,Adventure,7.7,Alexander Payne,Bruce Dern,112298,17654912.0,87.0
891,Incredibles 2,2018,118,Animation,7.6,Brad Bird,Craig T. Nelson,250057,608581744.0,80.0
66,WALLÂ·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
759,Changeling,2008,141,Biography,7.7,Clint Eastwood,Angelina Jolie,239203,35739802.0,63.0
759,Changeling,2008,141,Biography,7.7,Clint Eastwood,Angelina Jolie,239203,35739802.0,63.0
806,As Good as It Gets,1997,139,Comedy,7.7,James L. Brooks,Jack Nicholson,275755,148478011.0,67.0
870,Sabrina,1954,113,Comedy,7.7,Billy Wilder,Humphrey Bogart,59415,199534614.0,72.0
485,Un prophÃ¨te,2009,155,Crime,7.9,Jacques Audiard,Tahar Rahim,93560,2084637.0,90.0
41,The Usual Suspects,1995,106,Crime,8.5,Bryan Singer,Kevin Spacey,991208,23341568.0,77.0
468,"I, Daniel Blake",2016,100,Drama,7.9,Ken Loach,Laura Obiols,53818,258168.0,78.0
265,DÃ hÃ³ng denglong gaogao guÃ,1991,125,Drama,8.1,Yimou Zhang,Gong Li,29662,2603061.0,NaN
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
115,Per qualche dollaro in piÃ¹,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0

In [28]:
geners.nunique().sort_values

<bound method DataFrame.sort_values of            Series_Title  Released_Year  Runtime  IMDB_Rating  Director  Star1  \
Genre
Action              172             61       78           15       123    121
Adventure            72             49       58           10        59     59
Animation            82             35       41           11        51     77
Biography            88             44       56           13        76     72
Comedy              155             72       70           11       113    133
Crime               106             56       65           14        86     85
Drama               289             83       95           14       211    250
Family                2              2        2            1         2      2
Fantasy               2              2        2            2         2      2
Film-Noir             3              3        3            3         3      3
Horror               11             11       10            8        10     11
Mystery              12             11       10            8        10     11
Thriller              1              1        1            1         1      1
Western               4              4        4            4         2      2

           No_of_Votes  Gross  Metascore
Genre
Action             172    172         50
Adventure           72     72         33
Animation           82     82         29
Biography           88     88         40
Comedy             155    155         44
Crime              107    107         39
Drama              288    287         52
Family               2      2          2
Fantasy              2      2          0
Film-Noir            3      3          3
Horror              11     11          9
Mystery             12     12          7
Thriller             1      1          1
Western              4      4          4  >

In [29]:
geners.agg({
    'Runtime':'mean',
    'IMDB_Rating':'mean',
    
})

              Runtime  IMDB_Rating
Genre
Action     129.046512     7.949419
Adventure  134.111111     7.937500
Animation   99.585366     7.930488
Biography  136.022727     7.938636
Comedy     112.129032     7.901290
Crime      126.392523     8.016822
Drama      124.737024     7.957439
Family     107.500000     7.800000
Fantasy     85.000000     8.000000
Film-Noir  104.000000     7.966667
Horror     102.090909     7.909091
Mystery    119.083333     7.975000
Thriller   108.000000     7.800000
Western    148.250000     8.350000

In [36]:
geners.agg(['min','max','mean','sum'])

C:\Users\theve\AppData\Local\Temp\ipykernel_19108\1862340914.py:1: FutureWarning: ['Series_Title', 'Released_Year', 'Director', 'Star1'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  geners.agg(['min','max','mean','sum'])

          Runtime                         IMDB_Rating                         \
              min  max        mean    sum         min  max      mean     sum
Genre
Action         45  321  129.046512  22196         7.6  9.0  7.949419  1367.3
Adventure      88  228  134.111111   9656         7.6  8.6  7.937500   571.5
Animation      71  137   99.585366   8166         7.6  8.6  7.930488   650.3
Biography      93  209  136.022727  11970         7.6  8.9  7.938636   698.6
Comedy         68  188  112.129032  17380         7.6  8.6  7.901290  1224.7
Crime          80  229  126.392523  13524         7.6  9.2  8.016822   857.8
Drama          64  242  124.737024  36049         7.6  9.3  7.957439  2299.7
Family        100  115  107.500000    215         7.8  7.8  7.800000    15.6
Fantasy        76   94   85.000000    170         7.9  8.1  8.000000    16.0
Film-Noir     100  108  104.000000    312         7.8  8.1  7.966667    23.9
Horror         71  122  102.090909   1123         7.6  8.5  7.909091    87.0
Mystery        96  138  119.083333   1429         7.6  8.4  7.975000    95.7
Thriller      108  108  108.000000    108         7.8  7.8  7.800000     7.8
Western       132  165  148.250000    593         7.8  8.8  8.350000    33.4

          No_of_Votes                                          Gross  \
                  min      max           mean       sum          min
Genre
Action          25312  2303232  420246.581395  72282412       3296.0
Adventure       29999  1512360  313557.819444  22576163      61001.0
Animation       25229   999790  268032.073171  21978630     128985.0
Biography       27254  1213505  272805.045455  24006844      21877.0
Comedy          26337   939631  178195.658065  27620327       1305.0
Crime           27712  1826188  313398.271028  33533615       6013.0
Drama           25088  2343110  212343.612457  61367304       3600.0
Family         178731   372490  275610.500000    551221    4000000.0
Fantasy         57428    88794   73111.000000    146222  337574718.0
Film-Noir       59556   158731  122405.000000    367215     449191.0
Horror          27007   787806  340232.363636   3742556      89029.0
Mystery         33982  1129894  350250.333333   4203004    1035953.0
Thriller        27733    27733   27733.000000     27733   17550741.0
Western         65659   688390  322416.250000   1289665    5321508.0

                                                   Metascore         \
                   max          mean           sum       min    max
Genre
Action     936662225.0  1.897224e+08  3.263226e+10      33.0   98.0
Adventure  874211619.0  1.319017e+08  9.496922e+09      41.0  100.0
Animation  873839108.0  1.784326e+08  1.463147e+10      61.0   96.0
Biography  753585104.0  9.404952e+07  8.276358e+09      48.0   97.0
Comedy     886752933.0  1.010572e+08  1.566387e+10      45.0   99.0
Crime      790482117.0  7.899656e+07  8.452632e+09      47.0  100.0
Drama      924558264.0  1.225259e+08  3.540997e+10      28.0  100.0
Family     435110554.0  2.195553e+08  4.391106e+08      67.0   91.0
Fantasy    445151978.0  3.913633e+08  7.827267e+08       NaN    NaN
Film-Noir  123353292.0  4.197018e+07  1.259105e+08      94.0   97.0
Horror     298791505.0  9.405902e+07  1.034649e+09      46.0   97.0
Mystery    474203697.0  1.047014e+08  1.256417e+09      52.0  100.0
Thriller    17550741.0  1.755074e+07  1.755074e+07      81.0   81.0
Western     31800000.0  1.455538e+07  5.822151e+07      69.0   90.0


                mean      sum
Genre
Action     73.419580  10499.0
Adventure  78.437500   5020.0
Animation  81.093333   6082.0
Biography  76.240506   6023.0
Comedy     78.720000   9840.0
Crime      77.080460   6706.0
Drama      79.701245  19208.0
Family     79.000000    158.0
Fantasy          NaN      0.0
Film-Noir  95.666667    287.0
Horror     80.000000    880.0
Mystery    79.125000    633.0
Thriller   81.000000     81.0
Western    78.250000    313.0

In [39]:
# loop on group
for group,data in geners:
    print(data[data['IMDB_Rating']==data['IMDB_Rating'].max()])

      Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
2  The Dark Knight          2008      152  Action          9.0

            Director           Star1  No_of_Votes        Gross  Metascore
2  Christopher Nolan  Christian Bale      2303232  534858444.0       84.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
21  Interstellar          2014      169  Adventure          8.6

             Director                Star1  No_of_Votes        Gross  \
21  Christopher Nolan  Matthew McConaughey      1512360  188020017.0

    Metascore
21       74.0
                     Series_Title Released_Year  Runtime      Genre  \
23  Sen to Chihiro no kamikakushi          2001      125  Animation

    IMDB_Rating        Director          Star1  No_of_Votes       Gross  \
23          8.6  Hayao Miyazaki  Daveigh Chase       651376  10055859.0

    Metascore
23       96.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7  Schindler's List          1993      195  Biography          8.9

           Director        Star1  No_of_Votes       Gross  Metascore
7  Steven Spielberg  Liam Neeson      1213505  96898818.0       94.0
       Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
19     Gisaengchung          2019      132  Comedy          8.6
26  La vita Ã¨ bella          1997      116  Comedy          8.6

           Director            Star1  No_of_Votes       Gross  Metascore
19     Bong Joon Ho     Kang-ho Song       552778  53367844.0       96.0
26  Roberto Benigni  Roberto Benigni       623629  57598247.0       59.0
    Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1  The Godfather          1972      175  Crime          9.2

               Director          Star1  No_of_Votes        Gross  Metascore
1  Francis Ford Coppola  Marlon Brando      1620367  134966411.0      100.0
               Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
0  The Shawshank Redemption          1994      142  Drama          9.3

         Director        Star1  No_of_Votes       Gross  Metascore
0  Frank Darabont  Tim Robbins      2343110  28341469.0       80.0
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0

     Metascore
321        NaN
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating    Director  \
309  The Third Man          1949      104  Film-Noir          8.1  Carol Reed

            Star1  No_of_Votes     Gross  Metascore
309  Orson Welles       158731  449191.0       97.0
   Series_Title Released_Year  Runtime   Genre  IMDB_Rating          Director  \
49       Psycho          1960      109  Horror          8.5  Alfred Hitchcock

              Star1  No_of_Votes       Gross  Metascore
49  Anthony Perkins       604211  32000000.0       97.0
   Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69      Memento          2000      113  Mystery          8.4
81  Rear Window          1954      112  Mystery          8.4

             Director          Star1  No_of_Votes       Gross  Metascore
69  Christopher Nolan     Guy Pearce      1125712  25544867.0       80.0
81   Alfred Hitchcock  James Stewart       444074  36764313.0      100.0
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733  17550741.0       81.0
                       Series_Title Released_Year  Runtime    Genre  \
12  Il buono, il brutto, il cattivo          1966      161  Western

    IMDB_Rating      Director           Star1  No_of_Votes      Gross  \
12          8.8  Sergio Leone  Clint Eastwood       688390  6100000.0

    Metascore
12       90.0